# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 600)
        MainWindow.setMinimumSize(QtCore.QSize(720, 600))
        MainWindow.setMaximumSize(QtCore.QSize(720, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 711, 541))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.createSignal = QtWidgets.QAction(MainWindow)
        self.createSignal.setObjectName("createSignal")
        self.loadLocal = QtWidgets.QAction(MainWindow)
        self.loadLocal.setObjectName("loadLocal")
        self.menu.addAction(self.createSignal)
        self.menu.addAction(self.loadLocal)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "生理信号分析平台"))
        self.menu.setTitle(_translate("MainWindow", "创建生理信号"))
        self.menu_2.setTitle(_translate("MainWindow", "自定义预处理"))
        self.menu_3.setTitle(_translate("MainWindow", "自定义分析"))
        self.createSignal.setText(_translate("MainWindow", "创建模拟信号"))
        self.createSignal.setIconText(_translate("MainWindow", "创建模拟信号"))
        self.createSignal.setToolTip(_translate("MainWindow", "自定义一个模拟信号"))
        self.loadLocal.setText(_translate("MainWindow", "导入本地信号"))
        self.loadLocal.setToolTip(_translate("MainWindow", "导入本地信号"))
